### PR TITLE
Remove youtube-dl video archiving

### PR DESCRIPTION
**Pull request by jayjay-w**
## Description

Remove youtube-dl and all its references and tests since it is no longer supported.

Closes: CV2-3885

## How has this been tested?

- Made sure that `youtube-dl` does not come up anywhere in the codebase. 
- Running all tests should not raise any youtube specific errors

## Things to pay attention to during code review

Let me know whether there are any other bits related to youtube-dl that need to be removed and I may have missed them.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have added unit and feature tests, if the PR implements a new feature or otherwise would benefit from additional testing
- [x] I have added regression tests, if the PR fixes a bug
- [ ] I have added logging, exception reporting, and custom tracing with any additional information required for debugging
- [x] I considered secure coding practices when writing this code. Any security concerns are noted above.
- [x] I have commented my code in hard-to-understand areas, if any
- [x] I have made needed changes to the README
- [ ] My changes generate no new warnings
- [x] If I added a third party module, I included a rationale for doing so and followed our current [guidelines](https://meedan.atlassian.net/wiki/spaces/ENG/overview#Choose-the-%E2%80%9Cright%E2%80%9D-3rd-party-module)

### CODE REVIEW

**Comment by jayjay-w** [comment]
@caiosba / @vasconsaurus  this PR is from a fork, since my permissions for the repo are still being worked on. I wonder what the workflow is to trigger CI here since no checks were automatically run?

**Comment by caiosba** [comment]
> @caiosba / @vasconsaurus this PR is from a fork, since my permissions for the repo are still being worked on. I wonder what the workflow is to trigger CI here since no checks were automatically run?

Hum, I was checking here and I don't think it's easily possible... let's see how we can get you access quicker.

**Review by caiosba — APPROVED** [review]
Looks very complete! @vasconsaurus please review too.

**Comment by vasconsaurus** [comment]
@jayjay-w it looks very complete, I think you just missed a few tests in `archiver_test.rb`, while working on the archivers I skipped a bunch of them (`skip('we are not supporting archiving videos with youtube-dl anymore, will remove this on a separate ticket')`)

**Pull request closed without merging**
