### PR TITLE
Updated dead links, github repo name changes, and added nokogirl url

### PR DESCRIPTION
**Pull request by sabbatum**

### CODE REVIEW

**Comment by danielafeitosa** [comment]
Hi @sabbatum !
We appreciate the pull request but this doesn't add value to the project.
For Hacktoberfest PR's it's required to follow the [quality standars](https://hacktoberfest.digitalocean.com/details/#quality) and this PR is: 

> Something that's clearly an attempt to simply +1 your pull request count for October.

**Comment by sabbatum** [comment]
> 
> 
> Hi @sabbatum !
> We appreciate the pull request but this doesn't add value to the project.
> For Hacktoberfest PR's it's required to follow the [quality standars](https://hacktoberfest.digitalocean.com/details/#quality) and this PR is:
> 
> > Something that's clearly an attempt to simply +1 your pull request count for October.

That is not encouraging to a new user at all. I clearly did not make this to +1. I took time to go through all the links. I do not know how to program like you. If you don't want to merge it's okay, just close it but don't mark it as spam and don't fake being nice.

**Comment by danielafeitosa** [comment]
Hi @sabbatum,
Thank you for the time you took to go through all the links and fix them.
The file you changed is part of the project documentation. We have a file to generate the files on `doc`: https://github.com/meedan/pender/blob/develop/doc/Makefile
If you run it to update the `licenses.csv` and the other files it will be a nice contribution and we can remove the tags. Could you do it?

**Comment by sabbatum** [comment]
> 
> 
> Hi @sabbatum,
> Thank you for the time you took to go through all the links and fix them.
> The file you changed is part of the project documentation. We have a file to generate the files on `doc`: https://github.com/meedan/pender/blob/develop/doc/Makefile
> If you run it to update the `licenses.csv` and the other files it will be a nice contribution and we can remove the tags. Could you do it?

No. I am done with GitHub.

**Pull request closed without merging**
